export const PSL_TEAMS = [
  'Hyderabad Kingsmen',
  'Islamabad United',
  'Karachi Kings',
  'Lahore Qalandars',
  'Multan Sultans',
  'Peshawar Zalmi',
  'Quetta Gladiators',
  'Rawalpindi',
];

export const PSL_STADIUMS = [
  'Gaddafi Stadium, Lahore',
  'National Bank Cricket Arena, Karachi',
  'Rawalpindi Cricket Stadium, Rawalpindi',
  'Multan Cricket Stadium, Multan',
  'Iqbal Stadium, Faisalabad',
  'Arbab Niaz Stadium, Peshawar',
];

export const STADIUM_ENCLOSURES = {
  'National Bank Cricket Arena, Karachi': [
    { name: 'Iqbal Qasim', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Nasim-ul-Ghani', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Wasim Bari', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Mohammad Brothers', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Intikhab Alam', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Asif Iqbal', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Waqar Hasan', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Majid Khan', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Wasim Akram', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Zaheer Abbas', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Imran Khan', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Quaid', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Hanif Mohammad', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Javed Miandad', category: 'VIP', price: '0.30', capacity: '1000' },
  ],
  'Gaddafi Stadium, Lahore': [
    { name: 'Saeed Ahmad', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Inzamam-ul-Haq', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Nazars', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Quaid', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Imtiaz Ahmed', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Hanif Mohammad', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Sarfaraz Nawaz', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Abdul Qadir', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Abdul Hafeez Kardar', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Javed Miandad', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Saeed Anwar', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Rajas', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Fazal Mahmood', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Imran Khan', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Zaheer Abbas', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Majid Khan', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Waqar Younis', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Wasim Akram', category: 'VIP', price: '0.30', capacity: '1000' },
  ],
  'Rawalpindi Cricket Stadium, Rawalpindi': [
    { name: 'Sohail Tanvir', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Miran Bakhsh', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Shoaib Akhtar', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Yasir Arafat', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Azhar Mahmood', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Javed Miandad', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Javed Akhtar', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Imran Khan', category: 'VIP', price: '0.30', capacity: '1000' },
  ],
  'Multan Cricket Stadium, Multan': [
    { name: 'Elahi Brothers', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Mushtaq Ahmed', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Inzamam-ul-Haq', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Waqar Younis', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Wasim Akram', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Fazal Mahmood', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Zaheer Abbas', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Javed Miandad', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Imran Khan', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Main Pavilion', category: 'VVIP', price: '0.50', capacity: '300' },
  ],
  'Iqbal Stadium, Faisalabad': [
    { name: 'Shahid Nazir', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Waqar Younis', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Wasim Akram', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Zaheer Abbas', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Hanif Mohammad', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Taslim Arif', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Ijaz Ahmed Jnr', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Misbah-ul-Haq', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Fazal Mahmood', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Javed Miandad', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Imran Khan', category: 'VIP Ground Floor', price: '0.40', capacity: '500' },
    { name: 'A.H. Kardar', category: 'VIP Ground Floor', price: '0.40', capacity: '500' },
  ],
  'Arbab Niaz Stadium, Peshawar': [
    { name: 'East Gallery', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'West Gallery', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'North Stand', category: 'General', price: '0.10', capacity: '5000' },
    { name: 'Umar Gul', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Junaid Khan', category: 'First-Class', price: '0.15', capacity: '3000' },
    { name: 'Fakhar Zaman', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Yasir Shah', category: 'Premium', price: '0.20', capacity: '2000' },
    { name: 'Shahid Afridi', category: 'VIP', price: '0.30', capacity: '1000' },
    { name: 'Younis Khan', category: 'VIP', price: '0.30', capacity: '1000' },
  ],
};
